### ISSUE TITLE
Conflict with bullet threading

### ISSUE THREAD

**Issue by mzwlevi** [nmartin84/logseq-flow#14]
<img width="180" alt="Screen Shot 2022-10-27 at 18 38 43" src="https://user-images.githubusercontent.com/78029539/198270443-d63fa64e-81ed-49da-a7a5-f5c84c833d22.png">
<img width="178" alt="Screen Shot 2022-10-27 at 19 17 34" src="https://user-images.githubusercontent.com/78029539/198270649-9d71cee9-1c24-4cb7-85f2-816fbb7a48ac.png">

**Comment by nmartin84** [comment]
@mzwlevi - the bullet colors will change when a child block contains a task item. This is working as intended.
