### ISSUE TITLE
Load performance issue caused by external @imports

### ISSUE THREAD

**Issue by sethyuan** [nmartin84/logseq-flow#17]
Hi @nmartin84 , great theme, I like it very much!

Is it possible to remove the 2 `@import`s? Maybe internalize them? Or just removing them completely? Depending on network condition, they can impede the loading of the whole theme. It's kind of a real blocker where I live.

```css
@import url('https://fonts.googleapis.com/css?family=Raleway&display=swap');
@import url('https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css');
```

**Comment by nmartin84** [comment]
@sethyuan - i've embedded the font into the latest version (0.3.6) and removed the imports. Let me know if you have any other issues.

**Comment by sethyuan** [comment]
Thanks a lot!
