### ISSUE TITLE
Features not in same theme in settings

### ISSUE THREAD

**Issue by davidjaggi** [nmartin84/logseq-flow#21]
The features tab is in white in my case compared to green for the other tabs.

![image](https://user-images.githubusercontent.com/23697632/201635369-17252ffa-b1f3-450b-9efb-3259db85fb52.png)

**Comment by nmartin84** [comment]
@davidjaggi - thanks! i'll get a fix rolled out for this shortly.

**Comment by nmartin84** [comment]
Fix has been pushed in version 0.4.1
