### ISSUE TITLE
Navigation arrows not shown

### ISSUE THREAD

**Issue by franalbani** [nmartin84/logseq-flow#22]
When I chose this theme, I stop seeing them:
![image](https://user-images.githubusercontent.com/13975308/201762449-ffe3001e-7dbc-461a-a8cf-e9e40ada5dca.png)

**Comment by nmartin84** [comment]
Hi @franalbani - the screenshot you provided is from the awesome UI plugin by yoyurec. Here's a link to his github page = https://github.com/yoyurec/logseq-awesome-ui

**Comment by franalbani** [comment]
Sorry! I don't now how I mix them up.
