### ISSUE TITLE
Customization for both dark and light mode

### ISSUE THREAD

**Issue by karkraeg** [nmartin84/logseq-flow#31]
Hi, I would like to change two little things for myself: The Color of `.ls-block.selected` and the color of TODOs to make them stand out. If I change this in my custom.css it would only be one color for both a light and a dark version of your theme and if I change the main theme it will get overridden when you update the theme I guess. Can you help me how to customize this two values accordingly? Thanks!

**Comment by nmartin84** [comment]
Hi @karkraeg - you can customize the block-marker color by setting `--cl-marker-color: var(--cl-primary);` in your custom.css file:
```css
:root {
  --cl-marker-color: hsl(var(--cl-primary));
```

If you want to use one of the 3 colors defined in each theme then use any of the following variables: `--cl-primary`, `--cl-secondary`, `--cl-accent`. 

For `.ls-block.selected` I just added two new variables that'll control this element. They are `--cl-selected-background-color` and `--cl-selected-color` which have been added to version 0.4.7.
