### ISSUE TITLE
background of selected block is equal to link color so there is no distinction

### ISSUE THREAD

**Issue by jaroet** [nmartin84/logseq-flow#33]
Thans for the flow theme you build.
I like to change color often so I randomly choose a color (I have some favorites) every few days and the flow theme makes this very easy. 

But every theme included has the same 'flaw' and that is that the background of a selected block is the same as the highlight color of that theme. So when you have a block selected you do not see any links in it as the colors are the same. I slight change in the background (or the links for that matter) would make those visible.

I think that would be a great addition to this theme. Thank you. 

ADDED a few hours later : The same applies to all the dialogs (like t p (plugins) en t s (preferences). A somewhat different background color makes it clearer and less 'all over the place' (lack of a better term).

**Comment by nmartin84** [comment]
Hi @jaroet - you can adjust the color for the selected background color and color of the fonts. I've included a sample of what you would need to put in your custom.css file. With this change the blocks will use the secondary color defined in each color palette.

```css
:root {
  --cl-selected-background-color: var(--cl-secondary), 0.1;
  --cl-selected-color: var(--cl-secondary), 1;
}
```

Example screenshot where my selection color is secondary (green) and page-refs, highlights are primary (blue). 
![image](https://user-images.githubusercontent.com/38045018/215389213-ff23b03f-9ddd-486f-aacb-bf4ee6ee2c0f.png)

**Comment by jaroet** [comment]
Thanks for the CSS snippet but that does not seem to work when using dark-mode. 

![image](https://user-images.githubusercontent.com/28713432/215415282-0638f680-7a63-48e7-aabd-b0aad2ef3bd7.png)

Both rows are the same but in the second you can not see the [[test]] is a link.

**Comment by nmartin84** [comment]
@jaroet - it looks to me like your selection color has not changed. Which color palette are you using? And could you take a screenshot of that element from the dev tools? It should show something like the below:
![image](https://user-images.githubusercontent.com/38045018/215587763-7cead30d-980d-4e16-95d2-b4cc862d88bb.png)

**Comment by nmartin84** [comment]
Closing since this has gone stale. If you have the same issues still just comment here and we can reopen.
