### ISSUE TITLE
Bullet threading plugin circle is misaligned 

### ISSUE THREAD

**Issue by bezark** [nmartin84/logseq-flow#34]
Seems like there's an issue with the styling for bullet threading where the circle that used to be over the bullet is strangely offset.
![image](https://user-images.githubusercontent.com/14988649/217941776-b0a2f69b-6ae1-49b1-9c27-690d2d017e95.png)

**Comment by nmartin84** [comment]
@bezark yep this was expected - ill have it patched soon

**Comment by nmartin84** [comment]
I've throw a quick fix out that'll address the floating circle. Make sure you update and it should address your issue. There's still some alignment issues that need to be addressed.

**Comment by nmartin84** [comment]
Alignment issues have been fixed and will be included in next release
