### ISSUE TITLE
Nord Scheme

### ISSUE THREAD

**Issue by Bad3r** [nmartin84/logseq-flow#35]
Hello!
I love your theme & I love Nord scheme.
It looks like the current Nord variant of Logseq-Flow is
actually the One Dark theme and not Nord.

Please consider re-visiting the Nord variant.
I'll be more than happy to donate to your efforts to do so.
I don't see that you have GitHub sponsors setup.
Is there another way to support your work?

**Comment by nmartin84** [comment]
Hi @Bad3r - Nord had a incorrect lightness value applied to the BG color which I just pushed out a fix for so it matches the specs of nord. Let me know if you spot anything else off. Thanks.

**Comment by Bad3r** [comment]
Awesome, thank you for the quick response & update!  
  
Here is screenshots of before & after:

<table><tbody><tr><td>Before</td><td>After</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218208121-0116accd-84be-4d5b-ba0b-de544cabcaf9.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218208344-95c4b441-ec74-4949-8dd0-991d79041f22.png"></figure></td></tr></tbody></table>

  
I think it would be better if both the sidebar and the main panel had the same color like VS Code Nord Theme:

![](https://user-images.githubusercontent.com/25513724/218208570-3ca75e1a-a6bf-4dfe-bd91-fa5105335b6d.png)

Nord background color value: `#2e3440`

**Comment by Bad3r** [comment]
> **Note**
> 
> After making the sidebars colors uniform; I think its best to not change the text color of the selected item. Only change the background to `#434c5e`. In Nord scheme; white with different shades is used for text color. The light blue color used here is usually used for clickable links.   
>  
> 
> ![](https://user-images.githubusercontent.com/25513724/218209132-4cdfb3dc-06ad-4d2b-b4ed-d558df254f91.png)

**Comment by nmartin84** [comment]
Hi @Bad3r - thanks for the suggestions. I'll keep them in mind if I decide to revamp or make changes to any of those elements. As for the background for the side panels, everything uses a single color so its consistent all the way across. You may want to double check and make sure your theme is updated to the latest version, or you could have something conflicting and making that change.

![image](https://user-images.githubusercontent.com/38045018/218238558-af11225c-4e63-4089-84bd-c277fd8eb1f7.png)
