### ISSUE TITLE
Whitespace after external links; tag color after quote blocks

### ISSUE THREAD

**Issue by jsvensson** [nmartin84/logseq-flow#36]
Hi! Just came across this theme, and I'm really enjoying it. Came across a few things I figured I'd report:

- Linked text has a little bit of extra padding after the link, and just noticed that when the link is at the start of the block, there's also a little bit of padding before it.
- Using tags after a quote in the same block doesn't use the theme colors.

Screenshot provided, using the `Catpuccin Latte` theme.

![image](https://user-images.githubusercontent.com/450287/218261643-3b3cca93-ab28-42a5-80a1-a11e43ed559f.png)

**Comment by nmartin84** [comment]
External links are fixed. Also the tags showing up in gray is working as designed. The idea is to put tags that are inside the body, rather than the parent line in a neutral color. If it's a deal breaker I can add a change to make it customizable.

**Comment by jsvensson** [comment]
Thanks for the fix!

If the grayscale tags after quote blocks are intended, then no need to change it on my account, I'm fine with it as is.
