### ISSUE TITLE
release 0.6.8 is broken

### ISSUE THREAD

**Issue by st-binder** [nmartin84/logseq-flow#41]
the new release shows no bullet points (only squares) TODO keywords are not shortened and the task priority is vanished.

logseq 0.8.17
os: linux 64bit

**Comment by nmartin84** [comment]
Have you restarted Logseq? 0.6.8 changed the font-face family-name for tabler-icons to avoid conflicts with the built-in tabler-icons in logseq, but it may end up requiring a reboot of the app to recognize the new font name.

**Comment by st-binder** [comment]
Yes, logseq was restarted...

for `font-family: 'tabler-icons240';` in base.css I get:
- bulletpoints: ok
- TODO keywords: not shortened
- priority icons: vanished
change back to `font-family: 'tabler-icons';` I get:
- bulletpoints: empty squares
- TODO keywords: not shortened
- priority icons: visible, but not the same icons as for 0.6.7

**Comment by nmartin84** [comment]
Just released 0.6.9, try it out and let me know if it resolves your issues.

**Comment by st-binder** [comment]
Release 0.6.9 looks nice, only the priority icons look slightly different than before. Thank You!
