### ISSUE TITLE
The dots and lines are not vertically centered

### ISSUE THREAD

**Issue by huanhuanqiongqiong** [nmartin84/logseq-flow#44]
![image](https://user-images.githubusercontent.com/10186210/220865096-5b24872a-995d-455f-97d7-f840964a0792.png)

I update today and found this problem

**Comment by nmartin84** [comment]
Are you using this on mobile, or any plugins that changes the behavior of the guideline?

**Comment by huanhuanqiongqiong** [comment]
i am using it on windows 11, and the default theme don't have this problem, so i think it's not the plugins causes it.
by the way, 0.5.0 not have this problem
but for your information, I have plugins named Bullet Threading by pengx17 that changes it.

**Comment by nmartin84** [comment]
@huanhuanqiongqiong - so it can be a plugin since I have made changes to the bullet-container to work with tabler-icons. Try disabling or removing those plugins and it should work fine.

**Comment by nmartin84** [comment]
Also it looks like you have a modification to your guideline that changes the color based on the level of the block. You'll want to try disabling that as well.

**Comment by huanhuanqiongqiong** [comment]
![Uploading image.png…]()
it fixed, thx!
Definitely it's the plugin Bullet Threading by pengx17 that cause the problem
