### ISSUE TITLE
Dropdown arrow

### ISSUE THREAD

**Issue by cliffordx** [nmartin84/logseq-flow#6]
When opening a PDF for annotation, the header's dropdown arrow does not show up. It shows only when you close PDF.
<img width="200" alt="Screen Shot 2022-10-02 at 11 59 32 AM" src="https://user-images.githubusercontent.com/7141739/193437231-8a2f0be5-2c2f-4968-9e0a-e8b53e0dd5b4.png">

**Comment by cliffordx** [comment]
And, I would like to add. When you scroll the PDF, the scroll line bar does not show up. It does not happen when I switch to other themes. BTW, nice theme and I'm switching this theme back and forth with SolExt

**Comment by nmartin84** [comment]
Scrollbars are fixed now. Also, by drop down arrow are you referring to the block-control that appears to the left? 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/38045018/193462237-496425f8-0e50-4c94-b42f-37ad3fb9b03b.png">

**Comment by cliffordx** [comment]
> Scrollbars are fixed now. Also, by drop down arrow are you referring to the block-control that appears to the left?
> <img alt="image" width="105" src="https://user-images.githubusercontent.com/38045018/193462237-496425f8-0e50-4c94-b42f-37ad3fb9b03b.png">

Yes, that's what I mean. Please note this is when opening a PDF for annotation. 
I updated the theme just now but when I open the PDF this is what it look like:

<img width="610" alt="Screen Shot 2022-10-03 at 12 22 01 AM" src="https://user-images.githubusercontent.com/7141739/193465040-73cd5370-ce07-48fb-8dd2-0b9eb1caf36d.png">

It does not show up. And this is what looks like when I close the PDF:

<img width="320" alt="Screen Shot 2022-10-03 at 12 26 30 AM" src="https://user-images.githubusercontent.com/7141739/193465096-5e9392ce-ac08-49fe-bccc-2de587a3c9ea.png">

**Comment by nmartin84** [comment]
@cliffordx perfect thank you.. I think the container is clipping the arrow off the side. This should be easy to fix. I'll post when I have a pushed a fix for this. Thanks for reporting!

**Comment by nmartin84** [comment]
@cliffordx - So I have been testing this tonight but I can't reproduce what you are seeing. My window is getting the right amount of space so that my arrow is always visible when i'm annotating PDF files. Do you have any other plugins loaded or custom.css settings?

This is what mine looks like when I have a PDF open. I even tried setting the zoom factor to a crazy absurd high number but it's still showing fine:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/38045018/193946529-370d0390-c066-4e90-a480-7e3956cfcaaa.png">

**Comment by cliffordx** [comment]
@nmartin84  it's now working fine. I guess it's some other plugins (awesome links, sticky headers, awesome UI, and awesome stlyer) caused the issue and it was updated recently, so consider this issue now close. Thank you.
