### ISSUE TITLE
Highlighted text CSS not changing

### ISSUE THREAD

**Issue by angelineyeow** [nmartin84/logseq-flow#7]
Hi guys, thanks for all your work on this theme so far!

Would just like to feedback that the styling of the highlighted text remains the same (Logseq default - yellow highlight on black text) remains the same regardless of the theme applied.

Manually making these CSS changes using the global-css plugin (see below) resolves the issue for me, but was wondering if there was a way to make these changes permanent without having to use other plugins or do manual CSS changes.

```
/* mark {
    background: #fef3ac !important;
    color: #262626 !important;
}
*/
```

**Comment by angelineyeow** [comment]
Update: Not sure whether I jinx-ed it, but turning off the default styling for highlighted text doesn't work anymore :(

**Comment by nmartin84** [comment]
Hey @angelineyeow -- so I do have the highlighted portion defined in the theme, so if something is changing this setting then it's likely coming from a different plugin or custom setting. Are you familiar with how to use the developer console to inspect elements? If so, you can pull up the dev console and use the "Select an element" arrow to inspect the highlighted text. You should see something like the following below, the portion with an arrow is where the flow theme defines this setting. Feel free to share what you have on your side, and we can try to determine what's overriding this setting.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/38045018/193919916-ee3d2899-4c40-4b96-b676-c023a352fec4.png">

**Comment by angelineyeow** [comment]
Hi @nmartin84, sorry I missed this out! Realised it was an issue with the Text Wrapper plugin I was using since it relies on the == markdown syntax and somehow messes up the styling for normal highlighted text.

**Comment by nmartin84** [comment]
@angelineyeow - no worries!
