### ISSUE TITLE
Belafonte Day and Night

### ISSUE THREAD

**Issue by bezark** [nmartin84/logseq-flow#8]
Would love to see Belafonte Day and Night added.
I love all the colors you've added so far! 
![image](https://user-images.githubusercontent.com/14988649/194352003-d74ece77-e6c5-44f3-9e0d-55a7a17189d3.png)

**Comment by nmartin84** [comment]
@bezark - I just pushed out 0.1.5 which contains the new Belafonte color palette. Let me know if you have any feedback on the colors.

**Comment by bezark** [comment]
They look great! Thanks for doing that!
